name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Verify JAR exists
        run: ls -l target/*.jar

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
          if-no-files-found: error  # This will fail if no JARs are found
          
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: ./downloaded-jars
          
      - name: List downloaded files
        run: ls -l ./downloaded-jars
